#include <stdio.h>
#include <stdlib.h>//for using srand
#include <time.h> //for using time
#include <string.h> //for using strcmp

int difficulty(int choice){ // int becuse we have to  return max 
    int max;
    switch(choice){
        
        case 1:
        max= 10;
        break;
        
        case 2:
        max=50;
        break;

        case 3:
        max=100;
        break;

        default:
        printf("enter a valid choice");

        return -1;
    }
    return max;

}

int main(){

    srand(time(NULL));  //current time for random generator
    int r;  // number generated by program
    int x; //user  guess input 
    int attempts=0;
    int choice;
    char word[30];
   while(1){
     attempts=0;
     printf("-------------------------\n||    NUMBER GUESSING GAME  ||\n-------------------------\n");
     
     printf("choose difficulty \n  1-easy(1-10) \n 2-mid(1-50) \n 3-hard(1-100) \n");
     scanf("%d", &choice);
      int max=difficulty(choice);
       if(max==-1)
       {
        return 1;
        }
       r= rand()% max+1;
        if(choice==1){
            printf("-------------------------\n");
            printf("Difficulty: EASY\nRange: 1-10\nAttempts: 3\n -------------------------\n");
        }
        else if(choice==2){
            printf("Difficulty: MID\nRange: 1-50\nAttempts: 10\n -------------------------\n");
        }
        else{
            printf("Difficulty: HARD\nRange: 1-100\nAttempts:infinite \n -------------------------\n");
        }
        printf("I have choosen a number between 1 and %d \n", max);
        printf("||enter 0 to exit the game||\n");

     while(1){
        printf("|enter your guess|-\n ");
        scanf("%d", &x);
        
        if(x==0){
            printf("game over \n");
            break;

        }
        attempts++;

        //if guessed correct , come out from inner loop
        if(x==r){
            printf("you guessed it  bro\n");
            printf("you took %d attempts \n \n", attempts);
            break;
        }

        //attempts limits
        if((choice== 1 && attempts>=5)||(choice == 2 && attempts >= 10)){
           printf("ATTEMPTS OVER! YOU LOSE");
           break;
        }

        //if guessed wrong , hints
        else{
            if(x>r){
                printf("too high! guess lower \n");

            }

            else{
                printf("too low! guess higher \n");
            }
        }
     }
     printf("   \n press yes- to play again   \n no- to end\n");
     scanf("%29s", word);

     if(strcmp(word, "yes") == 0){
        continue;
        }
     else if(strcmp(word, "no") == 0){
        printf("thanks for playing\n ");
        break;
     }
     else
     printf("invalid reply nga");
    }
}
