#include <stdio.h>
#include <stdlib.h>
#include <time.h>
int main(){
    srand(time(NULL));  //current time for random generator
    int r;  // number generated by program
    int x; //user  guess input 
    int attempts=0;
    int difficulty;
    int max;
    printf("welcome to number guessing game\n");
    printf("----------------------------------\n");
    printf("choose difficulty \n  1-easy \n 2-mid \n 3-hard \n");
    scanf("%d", &difficulty);
    switch(difficulty){
        case 1:
        max= 10;
        break;
        
        case 2:
        max=50;
        break;

        case 3:
        max=100;
        break;

        default:
        printf("enter a valid choice");
        return 1;
    }

    r= rand()% max+1;
    printf("I have choosen a number between 1 and %d \n", max);
    printf("enter 0 to exit the game\n");
    while(1){
        printf("enter your guess-\n ");
        scanf("%d", &x);
        if(x==0){
            printf("game over \n");
            break;
        }
        attempts++;
        if(x==r){
            printf("you guessed it  bro \n");
            printf("you took %d attempts \n", attempts);
            break;

        }
        else{
            if(x>r){
                printf("too high! guess lower \n");

            }
            else{
                printf("too low! guess higher \n");
            }
        }
    }
}